# Site settings
title: Skyscanner
email: chris.behr@skyscanner.net
description: > # this means to ignore newlines until "baseurl:"
  Skyscanner is a leading global travel search site, providing instant online comparisons for millions of flights on over a thousand airlines, as well as car hire and hotels.
  Skyscanner’s flexible search options mean you can browse prices across a whole month, or even a year, allowing you to get the best deals. You always book direct with the airline or travel agent, so you get the lowest price, with no extra fees added.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://skyscanner.net" # the base hostname & protocol for your site
twitter_username: skyscanner
facebook_username: skyscanner
linkedin_username: skyscanner
youtube_username: skyscanner

# Build settings
markdown: kramdown
